### ISSUE TITLE
Toggle-button color

### ISSUE THREAD

**Issue by Aehrraid** [yasp-dota/yasp#527]
With my commits (https://github.com/yasp-dota/yasp/pull/526) a new minor issue appeared. Every toggle-button is darker, if collapsed. This is accomplished with:
```css
.toggle-button.collapsed {
  background-color...
}
```
**The problem:**
Every existing toggle-button (especially the Filter-buttons on every page) are not affected by this css-rule, because the .jade-source only states 'data-toggle="collapse"', not class="collapsed".
**The result:** (except player-histograms)
Initially toggle-buttons are not effected by css. They are light. But after uncollapsing and collapsing they become dark. Which is the correct state now.

**Comment by howardc93** [comment]
What is the expected behavior?

**Comment by Aehrraid** [comment]
Every toggle button is affected by .collapsed -> background-color: #545454;

**Comment by Aehrraid** [comment]
Could someone check, if this is an issue right now?

**Comment by howardc93** [comment]
I haven't noticed anything.  I merged your changes into my changeset earlier.  The `caching` branch should contain everything if you want to pull that and take a look.

**Comment by Aehrraid** [comment]
It is still present, but very tiny. Every toggle-button now has the **following behaviour** (wrong):
1. Collapsed. Light gray
   (CLICK)
2. Uncollapsed. Light gray
   (CLICK)
3. Collapsed. Dark gray

**Expected behaviour:**
1. Collapsed, dark gray
(CLICK)
2. Uncollapsed, light gray 
(CLICK)
3. Collapsed, dark gray

**Comment by howardc93** [comment]
Hmm.  Should we just give your buttons their own set of classes in order to prevent conflicts with the rest of the buttons (for which it's not as important to show toggled state?)

**Comment by Aehrraid** [comment]
We could do that!

**Comment by howardc93** [comment]
Fix incoming for this issue or is it minor enough to ignore?

**Comment by Aehrraid** [comment]
Ok, I will fix it!

**Comment by Aehrraid** [comment]
Ready for testing!
